
######################################################################################
######################### CREATE AND INSERT TABLE STATEMENTS #########################
######################################################################################


######################### OBJECTS #########################


CREATE TABLE Objects
(ID NUMBER(4) CONSTRAINT OBJECTS_ID_NN NOT NULL,
status VARCHAR2(7) DEFAULT 'storage',
type VARCHAR2 (10)  CONSTRAINT OBJECTS_TYPE_NN NOT NULL,
title VARCHAR2 (20) CONSTRAINT OBJECTS_TITLE_NN NOT NULL,
region VARCHAR2(15) DEFAULT 'UNKNOWN',
century NUMBER(4),
maker VARCHAR2(20) DEFAULT 'UNKNOWN',

CONSTRAINT OBJECTS_ID_PK PRIMARY KEY (ID)
);

INSERT ALL
INTO OBJECTS (ID, status, type, TITLE, REGION, century) VALUES (100, 'STORAGE', 'FINE_ART', 'KITCHEN STILL LIFE', 'FRANCE', 1400)
INTO OBJECTS (ID, status, type, TITLE, REGION, century, MAKER) VALUES (101, 'STORAGE', 'INSTRUMENT', 'CLOUDBUSTER', 'USA', 1900, 'WILHELM REICH')
INTO OBJECTS (ID, status, type, TITLE, REGION, century) VALUES (102, 'DISPLAY', 'INSTRUMENT', 'MICROSCOPE', 'RUSSIA', 1800)
INTO OBJECTS (ID, status, type, TITLE, REGION, century, MAKER) VALUES (103, 'DISPLAY', 'FINE_ART', 'WHITE ON WHITE', 'RUSSIA', 1900, 'KAZIMIR MALEVICH')
INTO OBJECTS (ID, status, type, TITLE) VALUES (104, 'DISPLAY', 'SPECIMEN', 'BAT WING')
INTO OBJECTS (ID, status, type, TITLE, REGION) VALUES (105, 'STORAGE', 'ARTEFACT', 'LIZARD FOSSIL', 'UGANDA')
INTO OBJECTS (ID, status, type, TITLE, REGION, century) VALUES (106, 'STORAGE', 'CRAFT', 'WICKER TABLE', 'IRELAND', 1900)
SELECT * FROM DUAL




######################### AREAS #########################


CREATE TABLE Areas
(ID NUMBER (3) CONSTRAINT AREAS_ID_NN NOT NULL,

CONSTRAINT AREAS_ID_PK PRIMARY KEY (ID)
);

INSERT ALL
INTO AREAS (ID) VALUES (100)
INTO AREAS (ID) VALUES (107)
INTO AREAS (ID) VALUES (112)
INTO AREAS (ID) VALUES (217)
INTO AREAS (ID) VALUES (302)
INTO AREAS (ID) VALUES (304)
INTO AREAS (ID) VALUES (311)
INTO AREAS (ID) VALUES (400)
INTO AREAS (ID) VALUES (500)
INTO AREAS (ID) VALUES (600)
INTO AREAS (ID) VALUES (700)
INTO AREAS (ID) VALUES (800)
SELECT * FROM DUAL




######################### STAFF #########################


CREATE TABLE staff
(ID NUMBER (5) CONSTRAINT STAFF_ID_NN NOT NULL,
first_name VARCHAR2 (10) CONSTRAINT STAFF_FIRSTNAME_NN NOT NULL,
last_name VARCHAR2 (15) CONSTRAINT STAFF_LASTNAME_NN NOT NULL,
email VARCHAR2 (25) CONSTRAINT STAFF_EMAIL_NN NOT NULL,
phone NUMBER (10) CONSTRAINT STAFF_PHONE_NN NOT NULL,
hourly_rate NUMBER (4,2) CONSTRAINT STAFF_RATE_NN NOT NULL,
speciality VARCHAR2 (20),
department VARCHAR2 (15),
licence_number NUMBER (8),
expiry_date DATE,
head_dept NUMBER(5),

CONSTRAINT STAFF_ID_PK PRIMARY KEY (ID),
CONSTRAINT STAFF_HEAD_FK FOREIGN KEY (head_dept) REFERENCES Staff(ID),
CONSTRAINT STAFF_LICENCE_UK UNIQUE (licence_number)
);

INSERT ALL
INTO STAFF (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HOURLY_RATE, SPECIALITY) 
VALUES (12745, 'FRANCISCO', 'GOYA', 'FGOYA@GMAIL.COM', 1594678512, 21.45, 'PAINTING')
INTO STAFF (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HOURLY_RATE, DEPARTMENT) 
VALUES (19482, 'MILTON', 'FRIEDMAN', 'MFRIED@GMAIL.COM', 0214751395, 99.99, 'ACCCOUNTS' )
INTO STAFF  (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HOURLY_RATE, DEPARTMENT, HEAD_DEPT) 
VALUES (19483, 'GORDON', 'GEKKO', 'GEKKO@GMAIL.COM', 1467582319, 99.99, 'ACCCOUNTS', 19482)
INTO STAFF (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HOURLY_RATE, LICENCE_NUMBER, EXPIRY_DATE) 
VALUES (34957, 'PATRICK', 'SARSFIELD', 'PSARS@GMAIL.COM', 0614571958, 16.90, 52465578, TO_DATE( '02/MAY/2017', 'DD/MON/YYYY'))
INTO STAFF (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HOURLY_RATE, LICENCE_NUMBER, EXPIRY_DATE, HEAD_DEPT) 
VALUES (61758, 'CHEVALIER', 'TESSE', 'CHEVT@GMAIL.COM', 0612497264, 16.91, 16472331, TO_DATE( '09/JUN/2017', 'DD/MON/YYYY'), 34957)
INTO STAFF (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, HOURLY_RATE, SPECIALITY, HEAD_DEPT) 
VALUES (43957, 'FRANCIS', 'BACON', 'FBACON@GMAIL.COM', 0168425560, 19.45, 'PAINTING', 12745)
SELECT * FROM DUAL




######################### EXHIBITIONS #########################


CREATE TABLE Exhibitions
(title VARCHAR2 (50) CONSTRAINT EXHIBITION_TITLE_NN NOT NULL,
start_date DATE CONSTRAINT EXHIBITION_START_NN NOT NULL,
finish_date DATE CONSTRAINT EXHIBITION_FINISH_NN NOT NULL,
num_visitors NUMBER (5) DEFAULT 0,

CONSTRAINT EXHIBITION_TITLE_PK PRIMARY KEY (title),
CONSTRAINT EXHIBITIONS_START_UK UNIQUE (start_date),
CONSTRAINT EXHIBITIONS_FINISH_UK UNIQUE (finish_date),
CONSTRAINT EXHIBITIONS_DATES_CK CHECK (start_date < finish_date)
);

INSERT ALL
INTO EXHIBITIONS (TITLE, start_date, finish_date, num_visitors) VALUES ('EARTH ROCKS : GEOLOGY AND INDUSTRY', TO_DATE( '13/FEB/2010', 'DD/MON/YYYY'), TO_DATE( '25/MAR/2010', 'DD/MON/YYYY'), 4756)
INTO EXHIBITIONS (TITLE, start_date, finish_date, num_visitors) VALUES ('COLOUR EXPLORED', TO_DATE( '02/APR/2010', 'DD/MON/YYYY'), TO_DATE( '28/APR/2010', 'DD/MON/YYYY'), 6421)
INTO EXHIBITIONS (TITLE, start_date, finish_date, num_visitors) VALUES ('NERVOUS ENERGY', TO_DATE( '14/MAY/2010', 'DD/MON/YYYY'), TO_DATE( '23/JUN/2010', 'DD/MON/YYYY'), 6148)
INTO EXHIBITIONS (TITLE, start_date, finish_date, num_visitors) VALUES ('CERAMICS CRACKED!', TO_DATE( '09/SEP/2010', 'DD/MON/YYYY'), TO_DATE( '13/OCT/2010', 'DD/MON/YYYY'), 3267)
INTO EXHIBITIONS (TITLE, start_date, finish_date, num_visitors) VALUES ('BUILDING BLOCKS : NATURAL STRUCTURES', TO_DATE( '01/NOV/2010', 'DD/MON/YYYY'), TO_DATE( '04/JAN/2011', 'DD/MON/YYYY'), 8706)
INTO EXHIBITIONS (TITLE, start_date, finish_date, num_visitors) VALUES ('HELLO : A HISTORY OF COMMUNICATIONS', TO_DATE( '26/JAN/2011', 'DD/MON/YYYY'), TO_DATE( '25/FEB/2011', 'DD/MON/YYYY'), 5759)
SELECT * FROM DUAL





######################### CATALOGUE ENTRIES #########################


CREATE TABLE Catalogue_Entries
(curators_note VARCHAR2 (1000) CONSTRAINT CATALOGUE_NOTE_NN NOT NULL,
OBJ_ID NUMBER (4) CONSTRAINT CATALOGUE_OBJ_NN NOT NULL,
EXB_Title VARCHAR2 (50) CONSTRAINT CATALOGUE_TITLE_NN NOT NULL,
AR_ID NUMBER (3) CONSTRAINT CATALOGUE_AREA_NN NOT NULL,

CONSTRAINT CATALOGUE_PK PRIMARY KEY (OBJ_ID, EXB_Title),
CONSTRAINT CATALOGUE_OBJ_FK FOREIGN KEY (OBJ_ID) REFERENCES Objects(ID),
CONSTRAINT CATALOGUE_TITLE_FK FOREIGN KEY (EXB_Title) REFERENCES Exhibitions(title),
CONSTRAINT CATALOGUE_AREA_FK FOREIGN KEY (AR_ID) REFERENCES Areas (ID)
);

INSERT ALL
INTO CATALOGUE_ENTRIES (curators_note, OBJ_ID, EXB_Title, AR_ID) VALUES ('Lorem ipsum dolor sit amet', 101, 'NERVOUS ENERGY', 112)
INTO CATALOGUE_ENTRIES (curators_note, OBJ_ID, EXB_Title, AR_ID) VALUES ('Lorem ipsum dolor sit amet', 100, 'BUILDING BLOCKS : NATURAL STRUCTURES', 217)
INTO CATALOGUE_ENTRIES (curators_note, OBJ_ID, EXB_Title, AR_ID) VALUES ('Lorem ipsum dolor sit amet', 104, 'BUILDING BLOCKS : NATURAL STRUCTURES', 302)
INTO CATALOGUE_ENTRIES (curators_note, OBJ_ID, EXB_Title, AR_ID) VALUES ('Lorem ipsum dolor sit amet', 105, 'BUILDING BLOCKS : NATURAL STRUCTURES', 304)
INTO CATALOGUE_ENTRIES (curators_note, OBJ_ID, EXB_Title, AR_ID) VALUES ('Lorem ipsum dolor sit amet', 102, 'BUILDING BLOCKS : NATURAL STRUCTURES', 311)
INTO CATALOGUE_ENTRIES (curators_note, OBJ_ID, EXB_Title, AR_ID) VALUES ('Lorem ipsum dolor sit amet', 106, 'BUILDING BLOCKS : NATURAL STRUCTURES', 107)
INTO CATALOGUE_ENTRIES (curators_note, OBJ_ID, EXB_Title, AR_ID) VALUES ('Lorem ipsum dolor sit amet', 103, 'BUILDING BLOCKS : NATURAL STRUCTURES', 112)
SELECT * FROM DUAL




######################### SHIFTS #########################


CREATE TABLE Shifts
(start_time DATE CONSTRAINT SHIFTS_START_NN NOT NULL,
finish_time DATE CONSTRAINT SHIFTS_FINISH_NN NOT NULL,
AR_ID NUMBER (3) CONSTRAINT SHIFTS_AREA_NN NOT NULL,
STF_ID NUMBER (5) CONSTRAINT SHIFTS_STAFF_NN NOT NULL,

CONSTRAINT SHIFTS_PK PRIMARY KEY (AR_ID, STF_ID, start_time),
CONSTRAINT SHIFTS_AREA_FK FOREIGN KEY (AR_ID) REFERENCES Areas(ID),
CONSTRAINT SHIFTS_STAFF_FK FOREIGN KEY (STF_ID) REFERENCES staff(ID)
);

INSERT ALL
INTO SHIFTS (start_time, finish_time, AR_ID, STF_ID) 
VALUES (TO_DATE('03/NOV/2010 10:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('03/NOV/2010 14:00', 'DD/MON/YYYY HH24:MI'), 800, 19482)
INTO SHIFTS (start_time, finish_time, AR_ID, STF_ID) 
VALUES (TO_DATE('03/NOV/2010 10:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('03/NOV/2010 17:00', 'DD/MON/YYYY HH24:MI'), 100, 34957)
INTO SHIFTS (start_time, finish_time, AR_ID, STF_ID) 
VALUES (TO_DATE('03/NOV/2010 10:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('03/NOV/2010 13:00', 'DD/MON/YYYY HH24:MI'), 100, 43957)
INTO SHIFTS (start_time, finish_time, AR_ID, STF_ID) 
VALUES (TO_DATE('03/NOV/2010 14:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('03/NOV/2010 17:00', 'DD/MON/YYYY HH24:MI'), 700, 19482)
INTO SHIFTS (start_time, finish_time, AR_ID, STF_ID) 
VALUES (TO_DATE('03/NOV/2010 14:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('03/NOV/2010 17:00', 'DD/MON/YYYY HH24:MI'), 100, 12745)
INTO SHIFTS (start_time, finish_time, AR_ID, STF_ID) 
VALUES (TO_DATE('03/NOV/2010 10:00', 'DD/MON/YYYY HH24:MI'), TO_DATE('03/NOV/2010 17:00', 'DD/MON/YYYY HH24:MI'), 400, 61758)
SELECT * FROM DUAL




######################### VISITORS #########################


CREATE TABLE Visitors
(ID NUMBER (5) DEFAULT 00000,
nationality VARCHAR2 (15) CONSTRAINT VISITORS_NATIONALITY_NN NOT NULL,
email VARCHAR2 (25) CONSTRAINT VISITORS_EMAIL_UK UNIQUE,
v_comment VARCHAR2 (400),
EXB_Title VARCHAR2 (50) CONSTRAINT VISITORS_EXHB_NN NOT NULL,

CONSTRAINT VISITORS_ID_PK PRIMARY KEY (ID),
CONSTRAINT VISITORS_EXHB_FK FOREIGN KEY (EXB_Title) REFERENCES Exhibitions(Title)
);

INSERT ALL
INTO VISITORS (ID, NATIONALITY, EMAIL, EXB_TITLE) VALUES (15486, 'GERMAN', 'MFRAT98@GMAIL.COM', 'BUILDING BLOCKS : NATURAL STRUCTURES')
INTO VISITORS (ID, NATIONALITY, EMAIL, EXB_TITLE) VALUES (15487, 'GERMAN', 'FRANZIFANZ@GMAIL.COM', 'BUILDING BLOCKS : NATURAL STRUCTURES')
INTO VISITORS (ID, NATIONALITY, V_COMMENT, EXB_TITLE) VALUES (15488, 'AMERICAN', 'VERY INTERESTING, BUT CONFUSINGLY LAID OUT', 'BUILDING BLOCKS : NATURAL STRUCTURES')
INTO VISITORS (ID, NATIONALITY, EMAIL, V_COMMENT, EXB_TITLE) VALUES (15489, 'IRISH', 'ITALIA90@GMAIL.COM', 'CLASS', 'BUILDING BLOCKS : NATURAL STRUCTURES')
INTO VISITORS (ID, NATIONALITY, EMAIL, EXB_TITLE) VALUES (15490, 'CHINESE', 'XIAOLAN@GMAIL.COM', 'BUILDING BLOCKS : NATURAL STRUCTURES')
INTO VISITORS (ID, NATIONALITY, V_COMMENT, EXB_TITLE) VALUES (15491, 'FRENCH', 'ENTERTAINING, BUT LACKING IN DEPTH', 'BUILDING BLOCKS : NATURAL STRUCTURES')
SELECT * FROM DUAL





####################################################################
######################### QUERY STATEMENTS #########################
####################################################################

##  All catalogue entries for a given exhibition (here 'Building Blocks: Natural Structures')
SELECT * FROM CATALOGUE_ENTRIES WHERE EXB_TITLE = 'BUILDING BLOCKS : NATURAL STRUCTURES'

##  All comments for a given exhibition, excluding null entries (here 'Building Blocks: Natural Structures')
SELECT V_COMMENT FROM VISITORS WHERE EXB_TITLE = 'BUILDING BLOCKS : NATURAL STRUCTURES' AND V_COMMENT IS NOT NULL

##  Information for the exhibition given a date (here 22 June 2010)
SELECT * FROM EXHIBITIONS WHERE START_DATE < '22/JUN/2010' AND FINISH_DATE > '22/JUN/2010'

##  Return names of staff who have worked in a specific location
SELECT FIRST_NAME, LAST_NAME FROM STAFF WHERE ID IN (SELECT STF_ID FROM SHIFTS WHERE AR_ID = 100)

##  Object Status for object ID / Title (here title = cloudbuster)
SELECT STATUS FROM OBJECTS WHERE TITLE = 'CLOUDBUSTER'

##  All objects for a given type in a given exhibition ( here type = 'fine art', exhibtion = 'Building Blocks: Natural Structures'
SELECT * FROM OBJECTS WHERE TYPE = 'FINE_ART' AND ID IN (SELECT OBJ_ID FROM CATALOGUE_ENTRIES WHERE EXB_TITLE = 'BUILDING BLOCKS : NATURAL STRUCTURES')

##  ID and title for all itmes currently on display
SELECT ID, TITLE FROM OBJECTS WHERE STATUS = 'DISPLAY'